// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.compiler.hilt

import dev.zacsweers.metro.compiler.compat.getStringArgumentCompat
import dev.zacsweers.metro.compiler.fir.annotationsIn
import dev.zacsweers.metro.compiler.fir.argumentAsOrNull
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.expressions.FirAnnotation
import org.jetbrains.kotlin.fir.expressions.FirCall
import org.jetbrains.kotlin.fir.expressions.FirLiteralExpression
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * Reads compiled Hilt `@AggregatedDeps` marker classes from [HiltSymbols.aggregatedDepsPackage].
 *
 * Source declarations from the current compilation are handled by [HiltComponentScopeMapping]; this
 * scanner is only for metadata generated by Hilt's own processors in upstream modules. Test-only
 * aggregated deps are ignored because Metro does not support `@TestInstallIn`.
 */
internal class HiltAggregatedDepsScanner(private val session: FirSession) {

  /** Materialized `@AggregatedDeps` annotation. */
  data class AggregatedDep(
    val components: List<ClassId>,
    val modules: List<ClassId>,
    val entryPoints: List<ClassId>,
    val replaces: List<ClassId>,
  )

  private val cached: List<AggregatedDep> by lazy { scan() }

  fun getAllDeps(): List<AggregatedDep> = cached

  private fun scan(): List<AggregatedDep> {
    val names =
      session.symbolProvider.symbolNamesProvider
        .getTopLevelClassifierNamesInPackage(HiltSymbols.aggregatedDepsPackage)
        .orEmpty()
    if (names.isEmpty()) return emptyList()

    val result = mutableListOf<AggregatedDep>()
    for (name in names) {
      val markerClassId = ClassId(HiltSymbols.aggregatedDepsPackage, name)
      val markerSymbol =
        session.symbolProvider.getClassLikeSymbolByClassId(markerClassId) as? FirRegularClassSymbol
          ?: continue
      val annotation =
        markerSymbol.annotationsIn(session, setOf(HiltSymbols.AggregatedDeps)).firstOrNull()
          ?: continue

      val test = annotation.getStringArgumentCompat(HiltNames.test, session).orEmpty()
      if (test.isNotEmpty()) continue

      result +=
        AggregatedDep(
          components =
            annotation
              .stringArrayArgument(session, HiltNames.components, index = 0)
              .mapNotNull(::resolveCanonicalName),
          modules =
            annotation
              .stringArrayArgument(session, HiltNames.modules, index = 3)
              .mapNotNull(::resolveCanonicalName),
          entryPoints =
            annotation
              .stringArrayArgument(session, HiltNames.entryPoints, index = 4)
              .mapNotNull(::resolveCanonicalName),
          replaces =
            annotation
              .stringArrayArgument(session, HiltNames.replaces, index = 2)
              .mapNotNull(::resolveCanonicalName),
        )
    }
    return result
  }

  /**
   * Hilt stores class-array values as canonical names with dots for package and nested-class
   * separators. Resolve by trying each possible package/class split against FIR symbols.
   *
   * This mirrors Dagger's own lookup through `env.findTypeElement(canonicalName)`.
   */
  private val canonicalNameCache = mutableMapOf<String, ClassId?>()

  private fun resolveCanonicalName(canonicalName: String): ClassId? {
    if (canonicalName.isBlank()) return null
    if (canonicalName in canonicalNameCache) {
      return canonicalNameCache[canonicalName]
    }
    val resolved = lookupCanonicalName(canonicalName)
    canonicalNameCache[canonicalName] = resolved
    return resolved
  }

  private fun lookupCanonicalName(canonicalName: String): ClassId? {
    val parts = canonicalName.split('.')
    if (parts.isEmpty()) return null

    // Try longest package first so top-level classes resolve before nested fallbacks.
    for (packageDepth in parts.size - 1 downTo 1) {
      val packageFqName = FqName.fromSegments(parts.subList(0, packageDepth))
      val relativeClassName = FqName.fromSegments(parts.subList(packageDepth, parts.size))
      val classId = ClassId(packageFqName, relativeClassName, /* isLocal= */ false)
      if (session.symbolProvider.getClassLikeSymbolByClassId(classId) != null) {
        return classId
      }
    }
    return null
  }
}

private fun FirAnnotation.stringArrayArgument(
  session: FirSession,
  name: Name,
  index: Int,
): List<String> {
  val call = argumentAsOrNull<FirCall>(session, name, index) ?: return emptyList()
  return call.argumentList.arguments.mapNotNull { (it as? FirLiteralExpression)?.value as? String }
}
