// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.compiler.hilt

import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionExtension
import dev.zacsweers.metro.compiler.fir.MetroFirTypeResolver
import dev.zacsweers.metro.compiler.memoize
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.types.constructClassLikeType
import org.jetbrains.kotlin.name.ClassId

/**
 * Contributes Hilt entry-point interfaces as FIR graph supertypes.
 *
 * This covers entry points declared in the current compilation and entry points listed in upstream
 * Hilt `@AggregatedDeps` metadata. Cross-module Metro-hinted entry points are handled by the normal
 * nested contribution interface generated by [HiltFirDeclarationExtension].
 */
public class HiltContributionExtension(private val session: FirSession) :
  MetroContributionExtension {

  private val scanner by memoize { HiltAggregatedDepsScanner(session) }

  /** Owns this extension's single-pass in-round `@InstallIn` scan. */
  private val componentScopes by memoize { HiltComponentScopeMapping(session) }

  override fun FirDeclarationPredicateRegistrar.registerPredicates() {
    register(HiltSymbols.installInPredicate)
  }

  override fun getContributions(
    scopeClassId: ClassId,
    typeResolverFactory: MetroFirTypeResolver.Factory,
  ): List<MetroContributionExtension.Contribution> {
    val contributions = mutableListOf<MetroContributionExtension.Contribution>()

    // Entry points recorded by upstream Hilt processors.
    for (dep in scanner.getAllDeps()) {
      if (dep.entryPoints.isEmpty()) continue
      if (dep.components.none { componentScopes.resolveScope(it) == scopeClassId }) continue
      for (entryPointClassId in dep.entryPoints) {
        contributions += contributionFor(entryPointClassId)
      }
    }

    // Entry points declared in this compilation.
    for (installIn in componentScopes.inRoundInstallIns) {
      if (!installIn.isEntryPoint) continue
      if (scopeClassId !in installIn.resolvedScopes(componentScopes)) continue
      contributions += contributionFor(installIn.classId)
    }

    return contributions
  }

  private fun contributionFor(entryPointClassId: ClassId): MetroContributionExtension.Contribution =
    MetroContributionExtension.Contribution(
      supertype = entryPointClassId.constructClassLikeType(emptyArray()),
      replaces = emptyList(),
      originClassId = entryPointClassId,
    )

  public class Factory : MetroContributionExtension.Factory {
    override fun create(
      session: FirSession,
      options: MetroOptions,
    ): MetroContributionExtension? {
      if (!options.enableHiltInterop || options.generateClassesInIr) return null
      return HiltContributionExtension(session)
    }
  }
}
